### ISSUE TITLE
bad prefix in one of the setup tests(?): 'kubernetes .. ' instead of 'multicluster ..' 

### ISSUE THREAD

**Issue by itay-nakash** [coredns/multicluster#10]
Hi guys,

I went through your setup_test.go file, and saw that the last test was config as 'kubernetes ..' instead of 'multicluster ...' in the plugin setup for the config map:
in `setup_test.go ` , line 34:
```
 `kubernetes coredns.local clusterset.local {
            fallthrough
             }`,
			false,
			"",
			2,
			fall.Root,
		},
```
other test cases were with a multicluster prefix, as I thought should be (for example):
```
		{
			`multicluster coredns.local clusterset.local`,
			false,
			"",
			2,
			fall.Zero,
		},
```
Is there a reason for the different prefixes? 
I hope this is the right place to write/ask about it,
Thanks.

**Comment by vanekjar** [comment]
I believe it may be a typo as the test is ported originally from https://github.com/coredns/coredns/blob/master/plugin/kubernetes/setup_test.go

Feel free to submit a PR to fix that.

**Comment by itay-nakash** [comment]
Great, I submitted a PR, 
Thanks.
