### ISSUE TITLE
error: cannot use e (type *Endpoints) as type "k8s.io/apimachinery/pkg/apis/meta/v1"

### ISSUE THREAD

**Issue by javierdompablo** [coredns/multicluster#9]
Hi guys,

I am having trouble compiling the project. When adding the plugin in the `plugin.cfg` list I get the following error:

```
# github.com/coredns/multicluster/object
/go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/object/endpoint.go:104:2: cannot use e (type *Endpoints) as type "k8s.io/apimachinery/pkg/apis/meta/v1".Object in return argument:
	*Endpoints does not implement "k8s.io/apimachinery/pkg/apis/meta/v1".Object (missing GetZZZ_DeprecatedClusterName method)
/go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/object/endpoint.go:152:2: cannot use e (type *Endpoints) as type "k8s.io/apimachinery/pkg/apis/meta/v1".Object in return argument:
	*Endpoints does not implement "k8s.io/apimachinery/pkg/apis/meta/v1".Object (missing GetZZZ_DeprecatedClusterName method)
/go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/object/namespace.go:31:2: cannot use n (type *Namespace) as type "k8s.io/apimachinery/pkg/apis/meta/v1".Object in return argument:
	*Namespace does not implement "k8s.io/apimachinery/pkg/apis/meta/v1".Object (missing GetZZZ_DeprecatedClusterName method)
```

go version go1.18.2

**Comment by runakash** [comment]
What is the coredns version?

**Comment by javierdompablo** [comment]
> What is the coredns version?

v1.9.2

**Comment by javierdompablo** [comment]
Test it with v1.8.7. It's works fine. Thanks!

**Comment by xh4n3** [comment]
@runakash I think PR https://github.com/coredns/multicluster/pull/8 is fixing the Issue https://github.com/coredns/multicluster/issues/7 .

To fix the error `missing GetZZZ_DeprecatedClusterName method`, we should implement methods `SetZZZ_DeprecatedClusterName` and `GetZZZ_DeprecatedClusterName` on `Namespace` and `Endpoints`, or we can update apimachinery vendor to this commit https://github.com/kubernetes/apimachinery/commit/430b920312ca0fa10eca95967764ff08f34083a3

**Comment by lauralorenz** [comment]
I did have this issue while first fixing #7, and as it seems this was a breaking change in 1.24 (see also https://github.com/coredns/coredns/pull/5364) that I didn't want to deal with at the time, I worked around it then by pinning to the prior 0.23.5 apimachinery version in coredns while developing. 

Oddly I'm not having this issue in my latest tests today though I'm now using apimachinery@0.24.2 from my latest coredns master branch rebase; which is earlier, and without the change in, https://github.com/kubernetes/apimachinery/commit/430b920312ca0fa10eca95967764ff08f34083a3, even though that change does look like the one we need 🤔

**Comment by xh4n3** [comment]
@lauralorenz Thanks for clarify this. 😃 
`apimachinery@0.24.2` should not work in anyway, that's odd, might be a dirty vendoring issue?
